# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: openjdk:8

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: casbin

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Build with Maven
        run: mvn clean test cobertura:cobertura

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}